name: Deploy

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - id: cache
        name: Yarn Cache Dir
        run: echo "::set-output name=value::$(yarn cache dir)"

      - name: Restore Lockfile
        uses: actions/cache@v2
        with:
          path: yarn.lock
          key: yarn-lock-${{ github.sha }}
          restore-keys: yarn-lock-

      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.cache.outputs.value }}
          key: yarn-cache-${{ github.sha }}
          restore-keys: yarn-cache-

      - name: Install
        run: yarn

      - name: Checkout koishi-plugin-dialogue
        uses: actions/checkout@v3
        with:
          repository: koishijs/koishi-plugin-dialogue
          path: .external/dialogue

      - name: Checkout koishi-plugin-eval
        uses: actions/checkout@v3
        with:
          repository: koishijs/koishi-plugin-eval
          path: .external/eval

      - name: Create Symlinks
        run: |
          ln -s ../.external/dialogue/docs ./community/dialogue
          ln -s ../.external/eval/docs ./community/eval

      - name: Build
        run: yarn build
        env:
          ENABLE_PWA: true

      - name: Deploy
        if: ${{ github.repository == 'koishijs/koishijs.github.io' && github.ref == 'refs/heads/docs' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .vuepress/dist
          publish_branch: pages
          force_orphan: true

  build-vercel:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - id: cache
        name: Yarn Cache Dir
        run: echo "::set-output name=value::$(yarn cache dir)"

      - name: Restore Lockfile
        uses: actions/cache@v2
        with:
          path: yarn.lock
          key: yarn-lock-${{ github.sha }}
          restore-keys: yarn-lock-

      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.cache.outputs.value }}
          key: yarn-cache-${{ github.sha }}
          restore-keys: yarn-cache-

      - name: Install
        run: yarn

      - name: Checkout koishi-plugin-dialogue
        uses: actions/checkout@v3
        with:
          repository: koishijs/koishi-plugin-dialogue
          path: .external/dialogue

      - name: Checkout koishi-plugin-eval
        uses: actions/checkout@v3
        with:
          repository: koishijs/koishi-plugin-eval
          path: .external/eval

      - name: Create Symlinks
        run: |
          ln -s ../.external/dialogue/docs ./community/dialogue
          ln -s ../.external/eval/docs ./community/eval

      - name: Build
        run: yarn build

      - name: Install vercel
        run: yarn global add vercel

      - name: Deploy vercel
        if: ${{ github.repository == 'koishijs/koishijs.github.io' && github.ref == 'refs/heads/docs' }}
        run: |
          rm .vuepress/dist/CNAME
          vercel deploy .vuepress/dist -n koishi-website --token ${{ secrets.VERCEL_TOKEN }} --prod --yes
